### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ghost** [flightcrank/pong#3]
Hi,

I'm interested in using this code for the libretro/RetroArch project and maybe elsewhere. I didn't see a license specified, but I noticed an old (closed) issue where you gave permission to someone else to use it.

Would you be ok with letting me/us use it as well? Thanks

**Comment by flightcrank** [comment]
sure thing you can use it. But from memory there are issues. it was simply an exercise in programming and to familiarise myself with the old SDL library.

- it uses the outdated SDL version 1.
- but its a little buggy, the ball can get caught on the end of a paddle
- the game never ends if i recall correctly

maybe ill update it in the near future. As its as simple as it gets really.

**Comment by flightcrank** [comment]
well I just updated this to work with SDL2 so should run on any modern system. The game does end i was wrong about that, its first to 10 points. The ai is a little rough but the ball will not get caught like i thought. Its been 7 years since i looked at the code so my memory was foggy.

oh it also now supports fullscreen mode with the "-f" command line argument.

enjoy
